name: math_keyboard_demo
description: Demo app for the math_keyboard package.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5
  flutter_math_fork: ^0.7.3
  math_parser: ^1.5.1

  math_keyboard:
    path: ../math_keyboard

  url_launcher: ^6.1.4
  url_strategy: ^0.2.0

dev_dependencies:
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/